autentikasi/urls.py
from django.urls import path

from . import views

app_name = 'autentikasi'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logoutUser, name='logout'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikasi.urls')),
]

autentikasi/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    full_name = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username   

autentikasi/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class  UserProfileForm(ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ['full_name']

        # full_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'full name'}))
        widget = {
            'full_name': forms.TextInput(attrs={'placeholder': 'name'}),
        }

autentikasi/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from . import forms, models
from .models import UserProfile

# Create your views here.
def index(request):
    #return render(request, 'autentikasi/index.html')
    if request.user.is_authenticated:
        name = UserProfile.objects.get(user = request.user)
        data = {
            'name' : name
        }
        return render(request, 'autentikasi/index-authenticated.html', data)
    else:
        return render(request, 'autentikasi/index.html')

def signup(request):
    user_form = forms.CreateUserForm()
    profile_form = forms.UserProfileForm()

    if request.method == 'POST':
        user_form = forms.CreateUserForm(request.POST)
        profile_form = forms.UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.save()
            profile = profile_form.save()
            profile.user = user
            profile.save()
            username = user_form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + username)
            return redirect('/signin')
    context = { 
        'form':user_form,
        'profile_form':profile_form,
    }
    return render(request, 'autentikasi/signup.html', context)

def signin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username or Password is Incorrect')

    return render(request, 'autentikasi/signin.html')

def logoutUser(request):
    logout(request)
    return render(request, 'autentikasi/signin.html')

autentikasi/templates/autentikasi/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/autentikasi.css' %}"> {% block meta %} {% endblock meta %}

    <style>
        .navbar {
            margin-bottom: 0;
            background-color: #F7FBE1;
            z-index: 9999;
            border: 0;
            font-size: 18px !important;
            line-height: 1.42857143 !important;
            letter-spacing: 4px;
            border-radius: 0;
        }
        
        .navbar li a,
        .navbar .navbar-brand {
            color: #436F8A !important;
            margin-left: 64px;
        }
        
        .navbar-nav li a:hover,
        .navbar-nav li.active a {
            color: white !important;
            background-color: #436F8A !important;
            border-radius: 22px;
        }
        
        .navbar-default .navbar-toggle {
            border-color: transparent;
            color: #fff !important;
        }
        
        @media screen and (max-width: 992px) {
            .navbar-toggle {
                margin-top: 55px;
            }
            .navbar-brand {
                font-size: 20px;
            }
        }
    </style>

</head>

<nav class="navbar navbar-default" style="margin-bottom:120px;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul style="margin-top:52px;" class="nav navbar-nav navbar-right">
                {% block home %}<li><a href="/">HOME</a></li>{% endblock home %}
                {% block sign %}
                <li id="sign"><a href="{% url 'autentikasi:logout' %}">SIGN OUT</a></li>{% endblock %}
            </ul>
        </div>
    </div>
</nav>

<body>
    {% block content %} {% endblock content %}
</body>

</html>

autentikasi/templates/autentikasi/index-authenticated.html
{% extends 'autentikasi/base.html' %} {% load static %} {% block meta %}
<title>Welcome, {{ name.full_name }}!</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/autentikasi.css' %}">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<style>
    .center {
        text-align: center;
        margin: auto;
    }
</style>
{% endblock meta %} {% block home %} {% endblock home %} {% block content %}
<div class="container-fluid">
    <div class="container center">
        <h1 id="welcome" style="color:#438A5E;font-size:40px;">Welcome</h1>
        <h1 id="name" style="color:#436F8A;font-size:60px;font-weight:bold;">{{ name.full_name }}</h1>
    </div>
</div>
{% endblock content %}

autentikasi/templates/autentikasi/index.html
{% extends 'autentikasi/base.html' %} {% load static %} {% block meta %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/autentikasi.css' %}">
<title>Welcome!</title>
<style>
    .center {
        text-align: center;
        margin: auto;
    }
    
    .btn-start {
        font-family: 'Poppins';
        font-style: normal;
        font-weight: bold;
        font-size: 30.7451px;
        line-height: 46px;
        text-decoration: none;
        background: #BAC964;
        border-radius: 30.7451px;
        padding: 7.69px 30.75px;
        color: #FFFFFF;
    }
</style>
{% endblock meta %} {%block home%}{%endblock home%} {% block sign %}{% endblock sign %} {% block content %}
<div class="container-fluid">
    <div class="container center">
        <h1 style="color:#438A5E;font-size:60px;">Welcome!</h1>
        <br>
        <a href="/signup/" class="btn btn-start">START NOW</a>
    </div>
</div>
</div>
{% endblock content %}

autentikasi/templates/autentikasi/signin.html
{% extends 'autentikasi/base.html' %} {% load static %} {% block meta %}
<title>Signin</title>
<link rel="stylesheet" href="{% static 'css/autentikasi.css' %}"> {% endblock meta %} {% block sign %}{% endblock %} {% block content %}
<div class="content">
    <div id="logindiv">
        <h2>Sign in to your account</h2>
        <form id="loginform" method="POST" action="">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <label for="username">Username</label>
            <input type="password" name="password" placeholder="Password">
            <label for="password">Password</label>
            <input type="submit" value="Sign in"> {% for message in messages %}
            <p class="errormsg">{{ message }}</p>
            {% endfor %}
        </form>
        <p class="hvacc">Didn't have any account yet? Sign up <a href="/signup/">Here</a></p>
    </div>
</div>
{% endblock content %}

autentikasi/templates/autentikasi/signup.html
{% extends 'autentikasi/base.html' %} {% load static %} {% block meta %}
<title>Signup</title>
<link rel="stylesheet" href="{% static 'css/autentikasi.css' %}"> {% endblock meta %} {% block sign %}{% endblock %} {% block content %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<div class="content">
    <div id="logindiv">
        <h2>Create Account</h2>
        <form id="loginform" method="POST" action="">
            {% csrf_token %} {{ form.non_field_errors }} {{ form.username.errors }} {{ form.username }}
            <label for="{{ form.username.id_for_label }}">Username</label> {{ profile_form.full_name}}
            <label for="{{ profile_form.full_name.id_for_label }}">Full Name</label> {{ form.email.errors }} {{ form.email }}
            <label for="{{ form.email.id_for_label }}">E-mail</label> {{ form.password1.errors }} {{ form.password1}}
            <label for="{{ form.password1.id_for_label }}">Password</label> {{ form.password2.errors }} {{ form.password2 }}
            <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
            <input type="submit" value="Sign up">
        </form>
        <p class="hvacc">Already have an account? Sign in <a href="/signin/">Here</a></p>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#id_username").attr('placeholder', 'Username');
        $("#id_email").attr('placeholder', 'E-mail');
        $("#id_full_name").attr('placeholder', 'Full Name');
        $("#id_password1").attr('placeholder', 'Password');
        $("#id_password2").attr('placeholder', 'Confirm Password');
    });
</script>
{% endblock content %}